# Generated by Django 3.2.7 on 2021-12-05 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Therapist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('inami_nb', models.CharField(max_length=20)),
                ('bank_account', models.CharField(max_length=20)),
                ('bce', models.CharField(max_length=20)),
                ('adress', models.TextField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
