# Generated by Django 3.2.7 on 2021-12-06 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapist',
            name='contracted',
            field=models.BooleanField(default=False),
        ),
    ]
