# Generated by Django 3.2.7 on 2021-12-08 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapist', '0002_therapist_contracted'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapist',
            name='activity',
            field=models.IntegerField(default=0),
        ),
    ]
