# Generated by Django 3.2.7 on 2022-01-13 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw', models.CharField(max_length=320)),
                ('name', models.CharField(max_length=320)),
            ],
        ),
        migrations.CreateModel(
            name='Nomenclature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Patho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw', models.CharField(max_length=320)),
                ('name', models.CharField(max_length=320)),
                ('breakpoints_encoded', models.CharField(max_length=64, null=True)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pathos', related_query_name='patho', to='timogen.location')),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='nomenclature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', related_query_name='location', to='timogen.nomenclature'),
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500, null=True)),
                ('kind', models.CharField(choices=[('INTAKE', 'Intake'), ('REPORT', 'Report'), ('CONSULT', 'Consultative'), ('DOUBLE', 'Double'), ('SECOND', 'Second'), ('MLD', 'Manual Lymphatic Drainage'), ('STANDARD', 'Others')], max_length=10)),
                ('priority', models.IntegerField(null=True)),
                ('duration', models.IntegerField(null=True)),
                ('code', models.CharField(max_length=10)),
                ('fees', models.FloatField(verbose_name='Standard Fees')),
                ('bfees_c_p', models.FloatField(verbose_name='Back fees (contracted + privileged)')),
                ('bfees_nc_p', models.FloatField(verbose_name='Back fees (not contracted + privileged)')),
                ('bfees_c_np', models.FloatField(verbose_name='Back fees (contracted + not privileged)')),
                ('bfees_nc_np', models.FloatField(verbose_name='Back fees (not contracted + not privileged)')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lines', related_query_name='line', to='timogen.location')),
                ('patho', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lines', related_query_name='line', to='timogen.patho')),
            ],
        ),
    ]
