# Generated by Django 4.0.1 on 2022-01-27 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timogen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='kind',
            field=models.CharField(choices=[('INTAKE', 'Intake'), ('REPORT', 'Report'), ('CONSULT', 'Consultative'), ('DOUBLE', 'Double'), ('SECOND', 'Second'), ('MLD', 'Manual Lymphatic Drainage'), ('STANDARD', 'Others')], max_length=32),
        ),
    ]
